### ISSUE TITLE
RawNet_weights.h5

### ISSUE THREAD

**Issue by aashiqmuhamed** [Jungjee/RawNet#1]
I'm wondering what network RawNet_weights.h5  provides weights for. Would you be able to provide the best model weights for both nets?

**Comment by Jungjee** [comment]
'data/RawNet_weights.h5' are used to extract speaker embeddings :).
But, since I have already uploaded extracted speaker embeddings at 'data/speaker_embeddings_RawNet_4.8eer', you can directly use those embeddings!

'data/RawNet_weights.h5' was uploaded upon a request from a researcher who wanted to extract speaker embeddings not from the VoxCeleb1 dataset but another dataset.

**Comment by aashiqmuhamed** [comment]
I'm planning on finetuning on VoxCeleb2 so I can't use your embeddings.

When I try using RawNet_weights.h5 with the CNN+GRU Rawnet model, it throws
ValueError: You are trying to load a weight file containing 33 layers into a model with 38 layers.

Just making sure the weights do correspond to the net defined in model_RawNet_pre_train.py

**Comment by Jungjee** [comment]
Do you mean model_RawNet.py? 
'model_RawNet_pre_train.py' refers to a CNN model which doesn't include GRU. 

Can you try loading the weights one more time using 'model_RawNet.py' instead of 'model_RawNet_pre_train.py'?

**Comment by aashiqmuhamed** [comment]
Sure my bad. Thank you!
