### ISSUE TITLE
Weights of RawNet2_modified trained on VoxCeleb2

### ISSUE THREAD

**Issue by CeLuigi** [Jungjee/RawNet#22]
Hi,

Can you kindly share the weights of _RawNet2_modified_ (trained on VoxCeleb2)?

Thank you very much

**Comment by Jungjee** [comment]
I have it somewhere in a hard drive that I used before, however, I'm not sure when I will have time to find them..
Meanwhile, I'll keep this issue open and let you know if I get to find it :)

**Comment by CeLuigi** [comment]
Hi, any news about this issue? Thank you very much

**Comment by Jungjee** [comment]
I didn't have the chance to look for it sorry :(

Since EER 1.9% in VoxCeleb1 testset became far from SOTA, 
I think I would rather reveal an updated model with a how to use tutorial.

But it would take time.. so meanwhile, it would better for you to use original RawNet2 and its weights it you don't mind :) 

Thanks.
