### ISSUE TITLE
Overfitting on VoxCeleb

### ISSUE THREAD

**Issue by Spectra456** [Jungjee/RawNet#28]
Hi.
I tried pre-trained RawNet on VoxCeleb and it's works better than ECAPA-TDNN pre-trained on VoxCeleb. But when i'm switching to another dataset on English(without training) or other languages it's works worst than ECAPA-TDNN, usually 2-4 times (EER). Do you have any ideas why it's happing? Thanks!

**Comment by Jungjee** [comment]
Hi @Spectra456.
The easiest thing to say would be that RawNet3 (I assume you used this one, since ECAPA-TDNN outperforms RawNet2) is somehow overfitted to VoxCeleb domain. 
However, it would be better to be cautious about making any claims at this point.

May I request for some additional information? such as the datasets you've tried, their corresponding EERs, minDCFs, ...

**Comment by Jungjee** [comment]
Please reopen this issue when you have further updates.
