### ISSUE TITLE
Why do we need this block of code?

### ISSUE THREAD

**Issue by ptJexio** [Jungjee/RawNet#8]
`out` after line 72 will always be overwritten
https://github.com/Jungjee/RawNet/blob/master/model_RawNet2.py#L66

`
if not self.first:
    out = self.bn1(x)
        out = self.lrelu_keras(out)
    else:
       out = x
`

**Comment by Jungjee** [comment]
You're right. 
Thank you ptJexio:)

I adjusted line 72.
Just re-ran the same experiment.
I will revise the EER if I see different performance.

Since the camera ready version due is 7 August,
If performance differs (It will probably improve? maybe?),
I will re-run relavant experiments and report it!

Again, thank you very much for pointing it out :)
